services:
    postgres:
      image: postgres:16-alpine
      container_name: db-catalogo
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432"
      volumes:
        - ./data:/var/lib/postgresql/data

    servico-catalogo:
      build: .
      container_name: servico-catalogo
      ports:
        - "8080:8080"
      environment:
        # Usa as variáveis do arquivo .env
        - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
        - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
        - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
        - API_SECURITY_TOKEN_SECRET=${API_SECRET}

      depends_on:
        - postgres


